name: r
description: A responsiveness helper to make your life easier.
version: 0.0.1
repository: https://github.com/edgarfroes/r

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
